### ISSUE TITLE
Samples quality generated from Pretrained model support

### ISSUE THREAD

**Issue by softrimewu** [lmnt-com/wavegrad#10]
Hi, 

I try to generate samples from your pretrained model, but the quality is not good. More specifically, the pitch is much higher than original sample, and many noise in the sample, like below
![image](https://user-images.githubusercontent.com/87403988/126256477-24d795c7-d759-4f21-8dd3-eb14fc86fe19.png)
![image](https://user-images.githubusercontent.com/87403988/126256493-b924e277-e0c8-428d-8b29-97005f3085e3.png)

Here is what I did:
1. clone repo
2. change hparam sample rate from 22050 to 24000
3. download reference audio you provided: https://lmnt.com/assets/wavegrad/24kHz
4. preprocess wav to extract mel with preprocess.py
5. inference from extracted mel and generate audio with inference.py
I didn't modify any code during this.
Could you please help have a look. Am I missing anything here?

Thanks

**Comment by sharvil** [comment]
I think the issue is the same as https://github.com/lmnt-com/wavegrad/issues/7#issuecomment-763200927. Can you try that and let me know if that works better for you?

**Comment by softrimewu** [comment]
> I think the issue is the same as [#7 (comment)](https://github.com/lmnt-com/wavegrad/issues/7#issuecomment-763200927). Can you try that and let me know if that works better for you?

It works.
Thank you!

**Comment by xw1324832579** [comment]
> > I think the issue is the same as [#7 (comment)](https://github.com/lmnt-com/wavegrad/issues/7#issuecomment-763200927). Can you try that and let me know if that works better for you?
> 
> It works. Thank you!

@softrimewu @sharvil Hi, I met the same problem as you, can you explain the solution in detail? Thank you so much.
I did the same steps as you and replaced the new preprocess.py in the fourth step, but the result was still noisy. 
Are there any other parameters to be modified besides the sampling rate？
