### ISSUE TITLE
how do i use it

### ISSUE THREAD

**Issue by potatoportato** [lmnt-com/wavegrad#16]
i ran this code
```py
import torchaudio
import wavegrad.inference
import librosa
import numpy as np
import IPython

waveform, sample_rate = torchaudio.load('CantinaBand3.wav')
sgram = librosa.stft(waveform.flatten().numpy())
mel_sgram = librosa.feature.melspectrogram(S=np.abs(sgram) ** 2, sr=sample_rate, n_fft=2048, hop_length=512, n_mels=128)
mel_sgram = librosa.amplitude_to_db(mel_sgram, ref=np.min)

audio, sample_rate = wavegrad.inference.predict(torch.from_numpy(mel_sgram), "wavegrad-24kHz.pt")
IPython.display.display(IPython.display.Audio(audio.flatten().detach().cpu().numpy(), rate=sample_rate))
```
the resulting audio file is high-frequency crackles and pops, not the cantina band
also, is this trained specifically for speech? is there anything for music or general audio? i can't train my own because my computer is not strong enough

**Comment by sharvil** [comment]
See https://github.com/lmnt-com/wavegrad/blob/master/src/wavegrad/preprocess.py#L39 for details on setting the right parameters to compute the spectrogram. Better yet, just use that code to produce the spectrograms.

The code is is trained on speech, yes. There's no pretrained model for music/general audio in this repository.
