### ISSUE TITLE
Hop size parameter

### ISSUE THREAD

**Issue by alexdemartos** [lmnt-com/wavegrad#4]
Hi, thanks for sharing your work with the community.

I saw your warning regarding the hop_samples parameter (hop_samples=300,  # Don't change this. Really.)

I was hoping you could give us a hint about what should we need to change in the code in order to work with different hop lengths.

Thank you!

**Comment by CookiePPP** [comment]
https://github.com/lmnt-com/wavegrad/blob/f46ca43e9cfc0cb8113560b97aacf524d797f721/src/wavegrad/model.py#L156-L160

See the 3rd arg in each layer?
5, 2, 2, 3, 5.
Those are the downsampling each layer performs to bring the input audio to the resolution of the spectrogram.
5 * 2 * 2 * 3 * 5 = 300 = hop_samples

---

Same thing on the upsampling layers
https://github.com/lmnt-com/wavegrad/blob/f46ca43e9cfc0cb8113560b97aacf524d797f721/src/wavegrad/model.py#L170-L174

5 * 5 * 3 * 2 * 2 = 300 = hop_samples

---

If you want to use `hop_samples` of 600, then you'd add another 2 layer or change a 2 to a 4.

e.g:
```python
        Conv1d(1, 32, 5, padding=2),
        DBlock(32, 128, 2),
        DBlock(128, 128, 2),
        DBlock(128, 256, 3),
        DBlock(256, 512, 5),
    ])
    self.film = nn.ModuleList([
        FiLM(32, 128),
        FiLM(128, 128),
        FiLM(128, 256),
        FiLM(256, 512),
        FiLM(512, 512),
    ])
    self.upsample = nn.ModuleList([
        UBlock(768, 512, 5, [1, 2, 1, 2]),
        UBlock(512, 512, 5, [1, 2, 1, 2]),
        UBlock(512, 256, 3, [1, 2, 4, 8]),
        UBlock(256, 128, 2, [1, 2, 4, 8]),
        UBlock(128, 128, 2, [1, 2, 4, 8]),
    ])
```
becomes
```python

    self.downsample = nn.ModuleList([
        Conv1d(1, 32, 5, padding=2),
        DBlock(32, 128, 2),
        DBlock(128, 128, 2), # <- new layer
        DBlock(128, 128, 2),
        DBlock(128, 256, 3),
        DBlock(256, 512, 5),
    ])
    self.film = nn.ModuleList([
        FiLM(32, 128),
        FiLM(128, 128), # <- new layer
        FiLM(128, 128),
        FiLM(128, 256),
        FiLM(256, 512),
        FiLM(512, 512),
    ])
    self.first_conv = Conv1d(160, 768, 3, padding=1)
    self.upsample = nn.ModuleList([
        UBlock(768, 512, 5, [1, 2, 1, 2]),
        UBlock(512, 512, 5, [1, 2, 1, 2]),
        UBlock(512, 256, 3, [1, 2, 4, 8]),
        UBlock(256, 128, 2, [1, 2, 4, 8]),
        UBlock(128, 128, 2, [1, 2, 4, 8]), # <- new layer
        UBlock(128, 128, 2, [1, 2, 4, 8]),
    ])
```

---

I don't know how to describe the input -> output dimensions of each layer, but you should get there with a bit of trail and error anyway.

**Comment by alexdemartos** [comment]
Thank you so much for your fast and very detailed response. I think it's perfectly clear. I'll give it a try, thanks again ;)
