### ISSUE TITLE
Multi-GPU Training does not seem to work

### ISSUE THREAD

**Issue by paranoid2droid** [lmnt-com/wavegrad#5]
Hi, thanks a lot for your awesome implementation!

However, I could not manage to train a model on multiple GPUs. I was trying to add `CUDA_VISIBLE_DEVICES=1,2,3` before the training command, but `nvidia-smi` showed that only the first GPU was working on the training.

Do you have any ideas on this issue? Is that the right way to use multi-GPU in this repo?

Thanks again!

**Comment by sharvil** [comment]
That's surprising – you shouldn't have to do anything more than setting `CUDA_VISIBLE_DEVICES` appropriately which it looks like you've already done.

Maybe you can check to see if `torch.cuda.device_count` is reporting the correct number of GPUs on your machine. Take a look at [`__main__.py`](https://github.com/lmnt-com/wavegrad/blob/master/src/wavegrad/__main__.py#L31) and add a print statement to make sure that it finds the right number of GPUs.

**Comment by paranoid2droid** [comment]
Sorry, it's my oversight. I was using the 0.1.3 version. I updated it and it works fine. Nice work!

**Comment by paranoid2droid** [comment]
Hi, I updated to the 0.1.4 version via pip, and it worked fine on multi-GPU training. However, it failed when I tried inference. I compared the codes between the pip version and git version and found that the pip version is missing chunks of codes. I think you may upgrade the pip to avoid this confusion. I appreciate a lot your work. Thanks!
