### ISSUE TITLE
Poor quality of samples

### ISSUE THREAD

**Issue by twoleggedeye** [lmnt-com/wavegrad#7]
Hi!
So, I am trying to do inference on VCTK with your pretrained model and getting some inconsistencies with resutls [here](https://lmnt.com/assets/wavegrad/24kHz/)
I am doing the following steps:
resample audio from 48kHz to 24 with sox 
```
sox <infile> -r 24000 <outfile>
```
change sample rate to 24000 [here](https://github.com/lmnt-com/wavegrad/blob/f46ca43e9cfc0cb8113560b97aacf524d797f721/src/wavegrad/params.py#L42)

Then I run preprocessing and inference as suggested in your readme
```
python -m wavegrad.preprocess ...
python -m wavegrad.inference ...
```
and get intelligible but heavily distorted samples with pitch shift-like distortion [example](https://drive.google.com/file/d/1CAa_vyhm3RVVYHow8RO_qPymtHtR4iRf/view?usp=sharing)

May be you have any suggestions of what could go wrong here?

**Comment by sharvil** [comment]
Good catch! Looks like a mismatch between the preprocessing code and pretrained model. If you replace the `transform` function of `inference.py` with the following code, it should work with the pretrained model:

```python
import librosa


def transform(filename):
  audio, sr = librosa.core.load(filename, sr=None)
  if params.sample_rate != sr:
    raise ValueError(f'Invalid sample rate {sr}.')
  audio = np.clip(audio, -1.0, 1.0)

  hop = params.hop_samples
  win = hop * 4
  n_fft = 2**((win-1).bit_length())
  f_max = sr / 2.0

  with torch.no_grad():
    spectrogram = librosa.feature.melspectrogram(y=audio, sr=sr, n_fft=n_fft, hop_length=hop, win_length=win, fmin=0, fmax=f_max, n_mels=128, power=1.0)
    spectrogram = torch.from_numpy(spectrogram.astype(np.float32))
    spectrogram = 20 * torch.log10(torch.clamp(spectrogram, min=1e-5)) - 20
    spectrogram = torch.clamp((spectrogram + 100) / 100, 0.0, 1.0)
    np.save(f'{filename}.spec.npy', spectrogram.cpu().numpy())
```

**Comment by twoleggedeye** [comment]
It helped, thanks a lot!
