### ISSUE TITLE
Not ImplementedError when inferencing on Google Colab

### ISSUE THREAD

**Issue by Koushik0901** [lmnt-com/wavegrad#8]
NotImplementedError                       Traceback (most recent call last)
<ipython-input-26-7645042be650> in <module>()
      3 model_dir = '/content/drive/MyDrive/MURF files/wavegrad-24kHz.pt'
      4 spectrogram = torch.FloatTensor(mels)
----> 5 audio, sample_rate = wavegrad_predict(spectrogram, model_dir)
      6 
      7 # audio is a GPU tensor in [N,T] format.

1 frames
/usr/local/lib/python3.7/dist-packages/wavegrad/inference.py in predict(spectrogram, model_dir, params, device)
     40 
     41   model = models[model_dir]
---> 42   model.params.override(params)
     43   with torch.no_grad():
     44     beta = np.array(model.params.noise_schedule)

/usr/local/lib/python3.7/dist-packages/wavegrad/params.py in override(self, attrs)
     29         self.override(attr)
     30     else:
---> 31       raise NotImplementedError
     32     return self
     33 

NotImplementedError:

**Comment by sharvil** [comment]
Thanks for the bugreport – fixed!
